CREATE TABLE CURSOS (
 Curso CHAR(4) NOT NULL,
 Nome_Curso VARCHAR(60) NOT NULL
);

ALTER TABLE CURSOS ADD CONSTRAINT PK_CURSOS PRIMARY KEY (Curso);


CREATE TABLE DISCIPLINAS (
 Disciplina CHAR(8) NOT NULL,
 Denominacao VARCHAR(60) NOT NULL,
 Nivel NUMERIC(3) NOT NULL,
 Curso CHAR(4)
);

ALTER TABLE DISCIPLINAS ADD CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (Disciplina);


CREATE TABLE PROFESSORES (
 Turma CHAR(3) NOT NULL,
 Ano_Sem CHAR(6) NOT NULL,
 Disciplina CHAR(8) NOT NULL,
 Professor VARCHAR(60) NOT NULL,
 Vagas NUMERIC(3)
);

ALTER TABLE PROFESSORES ADD CONSTRAINT PK_PROFESSORES PRIMARY KEY (Turma,Ano_Sem,Disciplina);


CREATE TABLE ALUNOS (
 Matricula NUMERIC(8) NOT NULL,
 Nome VARCHAR(60) NOT NULL,
 Sexo CHAR(1) NOT NULL,
 Idade NUMERIC(3) NOT NULL,
 Curso CHAR(4) NOT NULL
);

ALTER TABLE ALUNOS ADD CONSTRAINT PK_ALUNOS PRIMARY KEY (Matricula);


CREATE TABLE HISTORICOS (
 Turma CHAR(3) NOT NULL,
 Ano_Sem CHAR(6) NOT NULL,
 Matricula NUMERIC(8) NOT NULL,
 Disciplina CHAR(8) NOT NULL,
 Nota NUMERIC(3, 1) NOT NULL
);

ALTER TABLE HISTORICOS ADD CONSTRAINT PK_HISTORICOS PRIMARY KEY (Turma,Ano_Sem,Matricula,Disciplina);


ALTER TABLE DISCIPLINAS ADD CONSTRAINT FK_DISCIPLINAS_0 FOREIGN KEY (Curso) REFERENCES CURSOS (Curso);


ALTER TABLE PROFESSORES ADD CONSTRAINT FK_PROFESSORES_0 FOREIGN KEY (Disciplina) REFERENCES DISCIPLINAS (Disciplina);


ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS_0 FOREIGN KEY (Curso) REFERENCES CURSOS (Curso);


ALTER TABLE HISTORICOS ADD CONSTRAINT FK_HISTORICOS_0 FOREIGN KEY (Turma,Ano_Sem,Disciplina) REFERENCES PROFESSORES (Turma,Ano_Sem,Disciplina);
ALTER TABLE HISTORICOS ADD CONSTRAINT FK_HISTORICOS_1 FOREIGN KEY (Matricula) REFERENCES ALUNOS (Matricula);


